### ISSUE TITLE
not important but!

### ISSUE THREAD

**Issue by ahmetselman** [londonappbrewery/destini-challenge-completed#1]
in TODO Step 14 it has to be 

//TODO: Step 14 - Use the storyBrain to get the text for  **choice 2**.

Not

//TODO: Step 14 - Use the storyBrain to get the text for choice 1.

**Comment by John-Li** [comment]
Created PR: https://github.com/londonappbrewery/destini-challenge-completed/pull/2

**Comment by TheMuellenator** [comment]
Thanks for pointing this out. Fixed it now.
